navbar:
  blog_title: 红星网-马克思列宁主义论坛
  ground_glass:
    enable: true
index:
  banner_img: https://s1.ax1x.com/2022/05/03/OFTPtP.png
  banner_img_height: 100
  slogan:
    text: 青年一代，要正确把握时代主题与世界发展大势，就不得不学习马克思主义！
post:
  banner_img: https://s1.ax1x.com/2022/05/03/OFTpTI.jpg
  banner_img_height: 70
  default_index_img: https://s1.ax1x.com/2022/05/03/Ok98mt.jpg
archive:
  banner_img: https://s1.ax1x.com/2022/05/03/OFTkp8.jpg
  banner_img_height: 80
category:
  banner_img: https://s1.ax1x.com/2022/05/03/OFT31U.jpg
  banner_img_height: 80
tag:
  banner_img: https://s1.ax1x.com/2022/05/03/OFTS0A.jpg
  banner_img_height: 80
about:
  banner_img: https://s1.ax1x.com/2022/05/03/OFovOH.jpg
  banner_img_height: 80
  avatar: https://s1.ax1x.com/2022/05/03/Ok92hF.png
  name: 红星网
  intro: 马克思列宁主义论坛
links:
  banner_img: https://s1.ax1x.com/2022/05/03/OFTn7n.jpg
  banner_img_height: 80
  items:
    - title: 红星时事
      intro: 国内直连的西方媒体网站的文稿
      link: https://github.com/hongxing-chinese/news
      avatar: https://s1.ax1x.com/2022/05/03/Ok9l6A.png
    - title: 红星投稿
      intro: 如果你有任何想法，欢迎前往投稿模块写下你的想法
      link: https://hongxin-chinese-write.mysxl.cn/
      avatar: https://s1.ax1x.com/2022/05/03/Ok9mFO.png
    - avatar: https://s1.ax1x.com/2022/05/03/Ok9rmq.jpg
      link: https://imgtu.com/
      intro: 路过图床-高速稳定的图片上传和外链服务
      title: 路过图床
